# Generated by Django 5.0.1 on 2024-04-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='subname',
        ),
    ]
