# Generated by Django 5.0.2 on 2024-03-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_userinfo_password_userinfo_email_userinfo_pwd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
    ]
