# Generated by Django 5.0.2 on 2024-04-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_realcommoditycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
    ]
