# Generated by Django 5.0.1 on 2024-03-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
