# Generated by Django 5.0.2 on 2024-03-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_pwd_userinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
    ]
