# Generated by Django 5.0.1 on 2024-03-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
    ]
